### ISSUE TITLE
folgender Link geht nicht

### ISSUE THREAD

**Issue by rudgab** [iNaD/download-station-artemediathek#1]
http://concert.arte.tv/de/klavierabend-mit-maurizio-pollini-0

**Comment by iNaD** [comment]
Hi, entschuldige die späte Antwort, ich war im Urlaub.
Da es sich um keinen Arte+7 Link handelt, wird er zur Zeit auch nicht unterstützt. Ich werde mir das mal demnächst anschauen.

**Comment by rudgab** [comment]
Hi Daniel,

Vielleicht hatte ich den falschen Link markiert. Es war allerdings in der ARTE Mediathek.

Mit freundlichen Grüßen,

Rudolf Gabler
