### ISSUE TITLE
Download funktioniert nicht (Arte7)

### ISSUE THREAD

**Issue by BMuellerDE** [iNaD/download-station-artemediathek#10]
http://www.arte.tv/de/videos/046598-000-A/sand-die-neue-umweltzeitbombe

Vielen herzlichen Dank für dieses Tool :-) Klasse.

LG
Bernd

**Comment by iNaD** [comment]
Ich schließe hier mal, da die Links nicht mehr existieren und alle Mediatheken sich nun ein Projekt teilen: https://github.com/iNaD/ds-mediatheken
