### ISSUE TITLE
Arte video lädt nicht

### ISSUE THREAD

**Issue by EssElGhee** [iNaD/download-station-artemediathek#11]
Hi, ich benutze downloadstation und deine erweiterung. leider funktioniert das herunterladen nicht: https://www.arte.tv/de/videos/050375-000-A/tod-den-hippies-es-lebe-der-punk/

**Comment by iNaD** [comment]
Ich schließe hier mal, da die Links nicht mehr existieren und alle Mediatheken sich nun ein Projekt teilen: https://github.com/iNaD/ds-mediatheken
