### ISSUE TITLE
Arte Links funktionieren nicht

### ISSUE THREAD

**Issue by gwak64** [iNaD/download-station-artemediathek#2]
Hallo,
folgenden Link habe ich eingegeben: http://www.arte.tv/guide/de/051672-003/peaky-blinders-gangs-of-birmingham-3-6
herunter geladen wird stattdessen: 051672-003-A_EXT_SQ_1_VA-STA_01700108_MP4-2200_AMM-HBBTV_EXTRAIT.mp4

Ich habe hier eine 214Play mit der aktuellen DSM auf der z.B. die Scripte für die ARD- und ZDF-Mediatheken einwandfrei funktionieren.

Viele Grüße
Gerd

**Comment by iNaD** [comment]
Ich werde es mir anschauen.

**Comment by iNaD** [comment]
Hi Gerd,

Das ist auch korrekt so. Das ist ein 2 Minuten Ausschnitt, welcher auch als solcher auf der von dir angegebenen Seite deklariert ist.

Auch steht dort der Name der Folge und, dass die Ausstrahlung am 19.03. um 20:15 stattfindet.

```
PEAKY BLINDERS - GANGS OF BIRMINGHAM (3/6)

Auf der Rennbahn

Donnerstag, 19. März um 20:15 Uhr (56 Min.)
```

**Comment by gwak64** [comment]
Hallo Daniel,

unter dem erstgenannten Link kann ich mir die gesamte Folge ansehen. Erst
wenn ich diesen Link versuche in meine Diskstation zu transferieren, dann
erhalte ich nur den Ausschnitt. Bei ARD und ZDF klappt das jedenfalls
einwandfrei.
Irgendwie scheint die Mediathek von Arte anders organisiert zu sein. Ich
schaffe es nicht irgendeine von den 6 Folgen von Peaky Blinders auf meine
Diskstation zu laden.

Viele Grüße
Gerd

Daniel Gehn <notifications@github.com> schrieb am Mo., 16. März 2015 14:01:

Hi Gerd,

Das ist auch korrekt so. Das ist ein 2 Minuten Ausschnitt, welcher auch als
solcher auf der von dir angegebenen Seite deklariert ist.

Auch steht dort der Name der Folge und, dass die Ausstrahlung am 19.03. um
20:15 stattfindet.

PEAKY BLINDERS - GANGS OF BIRMINGHAM (3/6) Auf der Rennbahn Donnerstag, 19.
März um 20:15 Uhr (56 Min.)

**Comment by iNaD** [comment]
Unter dem Link kannst du dir sicher nicht die Folge ansehen, da diese noch nicht ausgestrahlt wurde. Die vorherigen Parts kann ich ohne Probleme herunterladen z.B. [Part 1](http://www.arte.tv/guide/de/051672-001/peaky-blinders-gangs-of-birmingham-1-6?autoplay=1), da erhalte ich eine über 1GB große Datei.

Bist du dir sicher, dass du die richtigen Links in die DS eingefügt hast?
