### ISSUE TITLE
Arte Mediathek Download funktioniert nicht

### ISSUE THREAD

**Issue by PotatoTony** [iNaD/download-station-artemediathek#4]
Hallo,
Ich wollte deine Arte Mediathek in Verbindung mit Synology probieren. Leider funktioniert der Download überhaupt nicht.
Ich habe sowohl diesen
http://www.arte.tv/guide/de/062446-000-A/ich-weiss-wer-du-bist
als auch diesen Link
http://www.arte.tv/guide/de/062446-000-A/ich-weiss-wer-du-bist#details-videos
probiert.

Hat beides nicht funktioniert. Mache ich was falsch?
Vielen Dank schon einmal.

Mfg
Tony

P.S. Habe eine DS 715 mit aktueller DS 5.x Software.

**Comment by iNaD** [comment]
Hi,
kann ich so bestätigen, ich schaue es mir mal an.

**Comment by iNaD** [comment]
So schnell kann es gehen. Arte hat mal wieder ein wenig was geändert an deren Seite.

[Mit dieser Version](https://github.com/iNaD/download-station-artemediathek/releases/latest) sollte es jetzt klappen. Bitte um Feedback ;)

**Comment by meinnamehier** [comment]
Funktioniert 
(getestet mit der URL http://www.arte.tv/guide/de/056821-002-A/360-geo-reportage)

**Comment by iNaD** [comment]
Super, dann mache ich hier erstmal dicht ;)

**Comment by PotatoTony** [comment]
Vielen Dank!
