### ISSUE TITLE
ARTE: Falsche Datei heruntergeladen

### ISSUE THREAD

**Issue by meinnamehier** [iNaD/download-station-artemediathek#5]
Auf einer DS215j mit DSM 5.2 wollte ich die Datei auf der Seite http://www.arte.tv/guide/de/056821-002-A/360-geo-reportage/ herunterladen.
Dabei wurde nicht das Video, sondern die Seite an sich heruntergeladen. Hostdatei für ARTE ist Version 0.2b

**Comment by iNaD** [comment]
Hallo meinnamehier,

das wurde bereits gemeldet (Siehe Issue #4).

Ich werde dieses Issue schließen, du kannst den Verlauf dann bei Issue #4 verfolgen.
