### ISSUE TITLE
Download der Sendungsseite statt Video

### ISSUE THREAD

**Issue by starchaser23** [iNaD/download-station-artemediathek#6]
Mit der Version 0.2c der artemediathek.host wird statt des Videos nur die HTML-Seite der Sendung heruntergeladen. Das scheint mit allen Videos der Fall zu sein, konkreter Testfall z.B. http://www.arte.tv/guide/de/057414-002-A/das-raetsel-unseres-bewusstseins-1-2

Umgebung:
DSM 6.0-7321 Update 3
Download Station 3.6-3277

**Comment by iNaD** [comment]
Hi, ich werde mich darum kümmern sobald ich Zeit habe. Ich hoffe es bis Sonntag Abend zu schaffen.

**Comment by iNaD** [comment]
Sollte wieder funktionieren

**Comment by bilke** [comment]
Mit Version 0.3a scheinbar das gleiche Problem. Z.B.:

http://www.arte.tv/guide/de/069108-000-A/der-jahrhundertprozess?country=DE

- DS916+
- DSM 6.0.2-8451 Update 1
- Download Station 3.7.3-3409

**Comment by iNaD** [comment]
Hi @bilke,
leider ist meine Synology immer noch außer Gefecht und mir fehlt die Zeit. Ich muss mal schauen, ob ich die nächsten Wochen dazu komme.

**Comment by iNaD** [comment]
Ich schließe hier mal, da die Links nicht mehr existieren und alle Mediatheken sich nun ein Projekt teilen: https://github.com/iNaD/ds-mediatheken
