### ISSUE TITLE
Kein Download bei arte+7 mehr möglich

### ISSUE THREAD

**Issue by starchaser23** [iNaD/download-station-artemediathek#9]
Arte hat den Aufbau der Sendungsdetailseiten geändert, der Download funktioniert leider nicht mehr. Bsp: http://www.arte.tv/guide/de/052421-003-A/die-ara-obama-3-4?country=DE

**Comment by iNaD** [comment]
Ich schließe hier mal, da die Links nicht mehr existieren und alle Mediatheken sich nun ein Projekt teilen: https://github.com/iNaD/ds-mediatheken
